version: '3.8'

volumes:
  collected_static: {}
  media: {}
  logs: {}

services:
   web:
       build:
           context: .
           dockerfile: ./compose/django/Dockerfile
       container_name: web_test_django
       command: python manage.py runserver 0.0.0.0:8010
       ports:
           - 8010:8010
       volumes:
         - collected_static:/webapp/collected_static:ro
         - media:/webapp/media:ro
         - logs:/webapp/logs:ro
